Feat: Inputs redesign
novasamatech/nova-spektr pull request #1028
Opened 2023-08-21 15:05 UTC by egor0798

## Changes:
* Input, search input, Input area and amount input redesign
* Changed default color for Icon and redesigned AssetIcon component
* Updated electron to 21.4.4
* Updated dev libraries
* Updated storybook for inputs
* Moved dropdown to input group
***
## Design
<img width="214" alt="image" src="https://github.com/novasamatech/nova-spektr/assets/27145216/0a1d4054-b17a-4eaf-8def-1af2a158c83f">

***
## Implementation
<img width="351" alt="image" src="https://github.com/novasamatech/nova-spektr/assets/27145216/ef6901e5-eb46-4034-918d-474e28d92215">

2023-08-22 12:01 UTC, tuul-wq requested changes

2023-08-23 11:04 UTC, egor0798 commented on src/renderer/entities/asset/ui/AssetIcon/styles.css
> +  background: var(--gr-border-primary);
Yeah, we can't use gadient with tailwind's bg cause bg turns into `background-color` but for linear gradient we need `background`. Tailwind has another mechanism for gradient but for that we'll need to define 3 separate variables - from color, to color and direction and I think we loose out agility with theming so I decided to do it in css file

2023-08-23 12:51 UTC, egor0798 commented on src/renderer/shared/ui/Inputs/Input/Input.tsx
> +            'focus-within:border-border-accent hover:focus-within:border-border-accent hover:border-border-secondary',
Moved styles but we still have some external usages - select components use `CommonInputStyles` cause they have exactly same style for select element itself. Do you think we should just copy same styles to select component?

2023-08-23 12:52 UTC, egor0798 commented on src/renderer/shared/ui/Buttons/common/constants.ts
> +  sm: 'h-6.5 rounded-[34px] text-body font-semibold',
This changes from typography request and displayed here cause of broken diff, so they're already in the base branch

2023-08-24 10:32 UTC, Asmadek approved these changes

2023-08-28 14:08 UTC, tuul-wq approved these changes

2023-08-28 14:42 UTC, merged