Feat: removed multishard wallets from signatory options
novasamatech/nova-spektr pull request #1102
Opened 2023-09-29 12:54 UTC by egor0798

2023-09-29 13:19 UTC, tuul-wq requested changes

2023-09-29 13:19 UTC, tuul-wq commented on src/renderer/entities/account/model/account.ts
> +import { AccountDS, ID, WalletDS } from '@renderer/shared/api/storage';
Wallet type is enough

2023-09-29 13:19 UTC, tuul-wq commented on src/renderer/entities/account/model/account.ts
> +  const notMultishard = !wallet || wallet.type !== WalletType.MULTISHARD_PARITY_SIGNER;
Better use positive variables accompanied with negative operator
```suggestion
  const isMultishard = wallet && wallet.type === WalletType.MULTISHARD_PARITY_SIGNER;
```

2023-09-29 13:19 UTC, tuul-wq commented on src/renderer/entities/account/model/account.ts
> +  return account.signingType !== SigningType.WATCH_ONLY && notMultishard && !isMultisig(account);
Would be great to add variable for this part of condition
```javascript
  const isWatchOnly = account.signingType === SigningType.WATCH_ONLY
```

2023-10-02 04:16 UTC, Asmadek approved these changes

2023-10-06 15:13 UTC, tuul-wq approved these changes

2023-10-09 08:41 UTC, merged