Feat: Multisig confirm update
novasamatech/nova-spektr pull request #1155
Opened 2023-10-17 15:22 UTC by egor0798

## Changes:
- Split details for multisig operation card and mutisig confirmation modal window into 2 separate component
- Updated mutisig confirmation modal window
  - Added sender or account display
  - Added multisig deposit display and cross chain fee

***

<img width="399" alt="image" src="https://github.com/novasamatech/nova-spektr/assets/27145216/bd7204fa-42bc-4bdb-9118-48be5ee44cdb">

2023-10-17 15:24 UTC, egor0798 commented on src/renderer/pages/Operations/components/ActionSteps/Confirmation.tsx
> +      {/*{isXcmTransaction(transaction) && xcmConfig && (*/}
Will be updated later

2023-10-18 05:21 UTC, Asmadek approved these changes

2023-10-18 05:21 UTC, Asmadek commented on src/renderer/pages/Operations/components/ActionSteps/Confirmation.tsx
> +      : tx.transaction;
maybe make some improvements for this code? Move it to function (this code uses in few places), create variable for find value, use array.includes for type detection

2023-10-18 05:21 UTC, Asmadek commented on src/renderer/pages/Operations/components/Details.tsx
> +        <DetailRow label={t('operation.details.' + hasSender ? 'sender' : 'account')} className="text-text-secondary">
```suggestion
        <DetailRow label={t(hasSender ? 'operation.details.sender' : 'operation.details.account')} className="text-text-secondary">
```
I think this way is more secure than string concatenation

2023-10-19 11:29 UTC, tuul-wq requested changes

2023-10-19 11:29 UTC, tuul-wq commented on src/renderer/pages/Operations/components/ActionSteps/Confirmation.tsx
> +  const xcmConfig = useStore(sendAssetModel.$finalConfig);
Better to use `useUnit` and move it 2 lines below
`const { t } = useI18n();` is a number 1 line in each component including translation 😉
```suggestion
  const xcmConfig = useUnit(sendAssetModel.$finalConfig);
```

2023-10-19 11:29 UTC, tuul-wq commented on src/renderer/pages/Operations/components/ActionSteps/Confirmation.tsx
> +          {xcmConfig && connection.api && (
`xcmConfig` has already been checked above - line `89`

2023-10-19 11:29 UTC, tuul-wq commented on src/renderer/pages/Operations/components/Details.tsx
>    const wallet = useUnit(walletModel.$activeWallet);
`activeWallet` attracts more attention

2023-10-19 11:29 UTC, tuul-wq commented on src/renderer/pages/Operations/components/OperationCardDetails.tsx
> +  const wallet = useUnit(walletModel.$activeWallet);
Same here
Checked other files, we stick to `activeWallet`

2023-10-19 11:29 UTC, tuul-wq commented on src/renderer/pages/Operations/components/OperationCardDetails.tsx
> +export default OperationCardDetails;
Prefer named export

2023-10-19 11:29 UTC, tuul-wq commented on src/renderer/pages/Operations/components/OperationFullInfo.tsx
> +import OperationCardDetails from '@renderer/pages/Operations/components/OperationCardDetails';
Import can be shortened

2023-10-19 11:29 UTC, tuul-wq commented on src/renderer/pages/Operations/components/modals/ApproveTx.tsx
> -          <>
👍

2023-10-19 11:29 UTC, tuul-wq commented on src/renderer/shared/ui/DetailRow/DetailRow.tsx
> +      <FootnoteText as="dd" align="right" className={cn('justify-end py-[3px] px-2', className)}>
👍 
can also change to `cnTw`

2023-10-19 13:42 UTC, tuul-wq requested changes
One code style change

2023-10-19 13:42 UTC, tuul-wq commented on src/renderer/entities/multisig/lib/multisigTx/common/utils.ts
> +export const getTransactionFromMultisigTx = (tx: MultisigTransaction): Transaction | DecodedTransaction | undefined => {
```javascript
export const getTransactionFromMultisigTx = (tx: MultisigTransaction): Transaction | DecodedTransaction | undefined => {
  if (!tx.transaction || tx.transaction.type !== 'batchAll') {
    return tx.transaction;
  }

  const transactionMatch = tx.transaction.args.transactions.find((tx: Transaction) => {
    return tx.type === TransactionType.BOND || tx.type === TransactionType.UNSTAKE;
  });

  return transactionMatch || tx.transaction.args.transactions[0];
};
```

2023-10-19 13:48 UTC, tuul-wq approved these changes

2023-10-19 13:58 UTC, merged