Feat: wallet connect details
novasamatech/nova-spektr pull request #1158
Opened 2023-10-18 11:13 UTC by Asmadek

2023-10-18 14:06 UTC, egor0798 commented on src/renderer/widgets/WalletDetails/ui/WalletConnectDetails.tsx
> +        <div className="flex items-center justify-between gap-x-2 py-5 px-5 border-b border-divider">
`py-5 px-5` => `p-5`

2023-10-18 14:07 UTC, egor0798 approved these changes

2023-10-19 08:12 UTC, tuul-wq requested changes
Suggestions

2023-10-19 08:12 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/WalletConnectDetails.tsx
> +      const account = accounts.find((a) => c.chainId === (a as WalletConnectAccount).chainId);
Not that important right now, but if have time and come up with a solution that is not N*N, that would be awesome 🤩
Maybe create a map of `accounts/chainIds`

2023-10-19 08:30 UTC, Asmadek commented on src/renderer/entities/walletConnect/model/wallet-connect-model.ts
> +    client.extend({ topic: s.topic }).catch((e) => console.warn(e));
it's just internal effect, we don't need to wait while it fulfilled

2023-10-19 09:11 UTC, tuul-wq requested changes

2023-10-19 09:11 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/model/wallet-provider-model.ts
> +const $connected = combine($accounts, walletConnectModel.$client, (accounts, client): boolean => {
```javascript
  const account = accounts[0];
  if (!client || !account || !accountUtils.isWalletConnect(account)) return false;
  
  // code
```

2023-10-19 09:15 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/WalletConnectDetails.tsx
> +  const accountsList = useMemo(() => {
Business logic is also about [data transformation](https://en.wikipedia.org/wiki/Business_logic#:~:text=Business%20logic%20is%20the%20portion%20of%20an%20enterprise%20system%20which%20determines%20how%20data%20is%20transformed%20or%20calculated%2C%20and%20how%20it%20is%20routed%20to%20people%20or%20software%20(workflow))

A good illustration of app's layers
![image](https://github.com/novasamatech/nova-spektr/assets/8149541/a6c95a7a-5b03-4bb0-8573-f5056fc7a8c8)

2023-10-19 13:22 UTC, tuul-wq approved these changes

2023-10-19 14:58 UTC, merged