Feat: wallet connect reconnect
novasamatech/nova-spektr pull request #1161
Opened 2023-10-19 14:56 UTC by Asmadek

2023-10-19 15:29 UTC, Asmadek commented
Task linked: [CU-8692u93cr Refresh Nova Wallet & WalletConnect wallet from details](https://app.clickup.com/t/8692u93cr)

2023-10-20 13:46 UTC, egor0798 approved these changes

2023-10-23 08:17 UTC, tuul-wq requested changes

2023-10-23 08:17 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/WalletConnectDetails.tsx
> +    if (isModalOpen) {
Looks to me that `reset` should be called on modal close
When model initiates we have a clean state, so there's actually nothing to reset
When we leave we reset so next time when open it's already clean

2023-10-23 08:17 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/WalletConnectDetails.tsx
> +  const isAccountsStep = reconnectStep === ReconnectStep.NOT_STARTED && connected;
⚠️ Logic in UI ⚠️
These flags should stay in model which knows how to produce them

2023-10-23 08:17 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/WalletConnectDetails.tsx
> +          isOpen={reconnectStep === ReconnectStep.REJECTED}
This flag goes to model as well

2023-10-23 08:17 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/WalletConnectDetails.tsx
> +    reconnectStarted();
Why not call `reconnectStarted` or `reconnected` pass all `connect` arguments there?
In model do reconnect stuff and then connect? 
Right not it's a logic in UI: we init connect (that's fine) but then UI somehow decides to call `reconnectStarted`

2023-10-23 08:17 UTC, tuul-wq commented on src/renderer/entities/walletConnect/model/wallet-connect-model.ts
>  type SessionTopicUpdateProps = {
I'd rather name it `SessionTopicParams`, `Props` is a react-world naming
effector is framework agnostic 😉

2023-10-23 10:54 UTC, Asmadek commented on src/renderer/features/operation/sign/ui/WalletConnect/WalletConnect.tsx
> +        walletConnectModel.events.currentSessionTopicUpdated(session?.topic);
Right, we have `sessionTopicUpdated`, where we should provide topic and accounts, and `currentSessionTopicUpdated` where we provide only topic

2023-10-24 08:22 UTC, tuul-wq requested changes

2023-10-24 08:22 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/common/const.ts
Let's move this file to `lib/constans.ts` according to FSD

2023-10-24 09:05 UTC, tuul-wq requested changes
A few comments to increase readability and maintainability 😉

2023-10-24 09:05 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/model/wallet-connect-details-model.ts
> +  fn: ({ accounts, session }) => ({
I guess this should work
```suggestion
fn: ({ accounts, session }) => ({ accounts, topic: session!.topic }),
```

2023-10-24 10:32 UTC, tuul-wq approved these changes

2023-10-24 11:00 UTC, merged