Feat: Disable auto update
novasamatech/nova-spektr pull request #1224
Opened 2023-11-07 15:07 UTC by egor0798

## Changes:
- added electron-store library to store `autoUpdate` flag

2023-11-08 06:56 UTC, pgolovkin requested changes

2023-11-08 06:56 UTC, pgolovkin commented on src/renderer/pages/Settings/Overview/components/GeneralActions/GeneralActions.tsx
> +      <Plate className="p-0">
This settings item has to be hidden for the web version.

2023-11-09 10:08 UTC, tuul-wq requested changes

2023-11-09 10:08 UTC, tuul-wq commented on package.json
> +  "version": "1.0.1",
Don't forget to rollback the version

2023-11-16 06:27 UTC, pgolovkin approved these changes

2023-11-17 08:10 UTC, tuul-wq approved these changes

2023-11-28 13:53 UTC, merged