Feat: balance refactoring
novasamatech/nova-spektr pull request #1270
Opened 2023-11-30 09:32 UTC by Asmadek

* Use `balance model` to work with balances
* use `balance subscription model` to work with balance subscriptions

Main changes in files
* src/renderer/entities/balance/model/balance-model.ts
* src/renderer/features/balances/model/balance-subscription-model.ts
* src/renderer/entities/balance/lib/common/utils.ts

2023-12-03 13:11 UTC, tuul-wq requested changes

2023-12-04 10:36 UTC, Asmadek commented on src/renderer/entities/balance/lib/balanceService.ts
> +export const useBalanceService = (): IBalanceService => {
create balance subscription service

2023-12-05 12:47 UTC, tuul-wq approved these changes

2023-12-05 12:47 UTC, tuul-wq commented on src/renderer/features/balances/model/balance-subscription-model.ts
> +// sample({
Can be removed?

2023-12-05 15:46 UTC, egor0798 commented on src/renderer/entities/balance/model/balance-model.ts
> +  timeout: 5000,
Maybe move it to const with some meaningful name?

2023-12-05 16:07 UTC, egor0798 approved these changes

2023-12-06 07:28 UTC, merged