Feat: Proxied wallet details
novasamatech/nova-spektr pull request #1365
Opened 2024-01-12 17:15 UTC by egor0798

Changes:
- Added wallet details for delegated to you (proxied) wallet
- Updated `WalletCardLg` height

***

<img width="439" alt="image" src="https://github.com/novasamatech/nova-spektr/assets/27145216/b308a103-40ff-4cff-b84e-201556680dcd">

2024-01-16 07:21 UTC, tuul-wq requested changes

2024-01-16 07:21 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/ProxiesList.tsx
> +  if (!proxyAccounts || !proxyAccounts.length) return <EmptyProxyList className={className} />;
`ProxiesList` responsibility is to display the list of proxies
It must know nothing about `EmptyList`
The condition that controls what component to display must be before `ProxiesList` or `EmptyProxiesList`

2024-01-16 07:21 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/ProxiesList.tsx
> +              className="-mt-10 -mr-1"
I don't like that for strange situations with negative margins we are forced to add `className` though we easily lived without it for a month or so
Could you provide a screenshot so we could discuss details and come up with another solution?

2024-01-16 07:21 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/ProxiesList.tsx
> +              explorers={chain.explorers || []}
It's `explorers = []` by default or it doesn't work without `|| []`?

2024-01-16 07:21 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/ProxiesList.tsx
> +          const chain = chainsService.getChainById(chainId);
`getChainById` is not a good function, I'll deprecate it one day
Better to get `networkModel.chains` and `chains[chainId]`

2024-01-16 07:21 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/ProxiesList.tsx
> +                        asset={chain?.assets[0]}
```suggestion
                        asset={chain.assets[0]}
```

2024-01-16 07:21 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/ProxiesList.tsx
> +                    {(proxiesByChain[chainId] || []).map((proxy) => (
At line `92` we've checked that `proxiesByChain[chainId]` has items

2024-01-16 07:21 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/ProxiesList.tsx
> +                          actionButton={getProxyActionButton(proxy, chain)}
You can create local component `ProxyAccountWithActions` move there `ProxyAccount` filled by `DropdownButton` actions without an additional function, pure jsx

2024-01-16 07:21 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/WalletConnectDetails.tsx
> +import { ProxiesList } from '@widgets/WalletDetails/ui/ProxiesList';
```suggestion
import { ProxiesList } from './ProxiesList';
```

2024-01-16 07:21 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/WalletConnectDetails.tsx
> +          {wcDetailsUtils.isNotStarted(reconnectStep, wallet.isConnected) && (
Would be great to create a dedicated component

2024-01-16 07:21 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/WalletDetailsProvider.tsx
> +import { ProxiedWalletDetails } from '@widgets/WalletDetails/ui/ProxiedWalletDetails';
```suggestion
import { ProxiedWalletDetails } from './ProxiedWalletDetails';
```

2024-01-16 07:21 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/VaultWalletDetails.tsx
> +import { ProxiesList } from '@widgets/WalletDetails/ui/ProxiesList';
```suggestion
import { ProxiesList } from './ProxiesList';
```

2024-01-16 13:33 UTC, egor0798 commented on src/renderer/shared/assets/images/arrows/curve-left-right.svg
yes "arrow-curve-left-right"

2024-01-16 13:41 UTC, egor0798 commented on src/renderer/shared/ui/Icon/data/functionals.tsx
> +  emptyListFile: { img: EmptyListImg, svg: EmptyListSvg },
We already have "emptyList" icon, but while looking fo that I found that the same icon I need here is already added and called "document"

2024-01-17 06:09 UTC, tuul-wq requested changes

2024-01-17 06:09 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/MultishardWalletDetails.tsx
> +        <EmptyProxyList className="h-[393px] mt-4" />
Let's name it `<NoProxiesAction />` and move to local `ui` folder

2024-01-17 06:09 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/MultisigWalletDetails.tsx
> +import { walletProviderModel } from '@widgets/WalletDetails/model/wallet-provider-model';
import can be shortened

2024-01-17 06:09 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/ProxiesList.tsx
> -  if (!proxyAccounts || !proxyAccounts.length) return <EmptyProxyList className={className} />;
Excellent 👍

2024-01-17 06:09 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/VaultWalletDetails.tsx
> +import { walletProviderModel } from '@widgets/WalletDetails/model/wallet-provider-model';
shorten import

2024-01-17 07:34 UTC, tuul-wq requested changes

2024-01-17 07:34 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/wallets/MultishardWalletDetails.tsx
> +import { ProxiesList } from '@widgets/WalletDetails/ui/components/ProxiesList';
Short imports

2024-01-17 07:35 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/components/WalletConnectAccounts.tsx
> +    const sortedChains = chainsService.sortChains(Object.values(chains));
Chains are already sorted in `networkModel`
line 12 `const chains = chainsService.getChainsMap({ sort: true });`

2024-01-17 11:59 UTC, tuul-wq reviewed
Requires one last change

2024-01-17 11:59 UTC, tuul-wq commented on src/renderer/entities/wallet/ui/MultishardAccountsList/MultishardAccountsList.tsx
> +  const chains = useUnit(networkModel.$chains);
Please move `chains` to props

2024-01-17 11:59 UTC, tuul-wq commented on src/renderer/shared/core/index.ts
> +export { ProxyType, ProxyVariant } from './types/proxy';
This import was grouped with other Proxy types, now it's separated
Please move it back

2024-01-17 11:59 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/ui/components/NoProxiesAction.tsx
> +export const NoProxiesAction = ({ className }: Props) => {
Nice 👍

2024-01-17 12:40 UTC, tuul-wq approved these changes

2024-01-17 14:49 UTC, tuul-wq approved these changes
With tiny suggestion

2024-01-17 14:49 UTC, tuul-wq commented on src/renderer/entities/proxy/lib/__tests__/utils.test.ts
> +import { expect } from '@playwright/test';
We use jest to `expect` not `playwright`

2024-01-17 14:49 UTC, tuul-wq commented on src/renderer/entities/proxy/lib/__tests__/utils.test.ts
> +    expect(sortedAccounts.map((a) => a.proxyType)).toEqual([
Why not this?
```javascript
expect(sortedAccounts).toEqual([proxyAccounts[2], proxyAccounts[0], proxyAccounts[1]]);
```

2024-01-17 14:49 UTC, tuul-wq commented on src/renderer/widgets/WalletDetails/model/__tests__/walet-provider-model.test.ts
> +import { walletProviderMock } from '@widgets/WalletDetails/model/__tests__/wallet-provider.mock';
```suggestion
import { walletProviderMock } from './wallet-provider.mock';
```

2024-01-17 17:35 UTC, merged