feat: decode proxy transactions
novasamatech/nova-spektr pull request #1380
Opened 2024-01-23 08:07 UTC by Asmadek

* support proxy pallet in call data decoder and extrinsic service 
* add tests for call data decoder and extrinsic service

2024-01-24 13:23 UTC, egor0798 commented on src/renderer/entities/transaction/lib/__tests__/extrinsicService.test.ts
> +  test.each([
`test.each`  does not provide great readability so I think you should move test data to separate file and create some type with meaningfull names. You can check `src/renderer/features/wallets/ImportKeys/lib/__tests__/import-keys-utils.test.ts` test there is a similar scenario
There is a type for test data
```
type ValidationTestData = {
  testName: string;
  derivation: DerivationWithPath;
  isValid: boolean;
};
```

and  that's how it used in test
```
test.each(importKeysMocks.shouldIgnoreDerivationTestData)('$testName', ({ derivation, shouldIgnore }) => {
      expect(importKeysUtils.shouldIgnoreDerivation(derivation)).toEqual(shouldIgnore);
    });
```

2024-01-24 13:29 UTC, egor0798 requested changes
Would be great if you improve test data format for `extrinsicService.test.ts`.
comment link:
https://github.com/novasamatech/nova-spektr/pull/1380/files#r1464908210

2024-01-26 07:06 UTC, tuul-wq approved these changes

2024-01-26 07:06 UTC, tuul-wq commented on src/renderer/entities/transaction/lib/callDataDecoder.ts
> +          threshold: decoded.args[0].toString(),
By the way, why you appended `.toString`? Something was wrong without it?

2024-01-26 07:06 UTC, tuul-wq commented on src/renderer/shared/lib/utils/constants.ts
> +export const TEST_ACCOUNT_ID_2 = '0x83e0844510ede3aea6953c9886d9a51abdd944b6395de7b83bbce6dffce0c765';
Better to group with existing `TEST_ACCOUNT_ID`

2024-01-26 11:03 UTC, Asmadek commented on jest-setup.js
> +    getRandomValues: (arr) => crypto.getRandomValues(arr),
`MockProvider` requires it

2024-01-26 11:10 UTC, Asmadek commented on src/renderer/entities/transaction/lib/callDataDecoder.ts
> +          threshold: decoded.args[0].toString(),
We don't decode multisig txs before (only call data), and without transform it doesn't work

2024-01-26 12:22 UTC, egor0798 approved these changes

2024-01-29 08:41 UTC, merged