Fix: updated unique derivation path validation
novasamatech/nova-spektr pull request #1437
Opened 2024-02-08 11:34 UTC by egor0798

## Changes:
- Validate derivation path to be unique only with keys in same network

2024-02-08 11:35 UTC, egor0798 commented
closes [1431](https://github.com/novasamatech/nova-spektr/issues/1431)

2024-02-08 11:45 UTC, pgolovkin commented
@egor0798 import is not fixed. I'm getting error that keys are duplicated.

2024-02-09 05:28 UTC, Asmadek approved these changes

2024-02-09 06:40 UTC, tuul-wq requested changes

2024-02-09 06:40 UTC, tuul-wq commented on src/renderer/features/wallets/KeyConstructor/model/constructor-model.ts
> +              return keyToCheck.chainId !== network.chainId || !keyToCheck.derivationPath.includes(value);
This is important, better to have test covering this rule

2024-02-12 07:07 UTC, tuul-wq approved these changes

2024-02-12 07:07 UTC, merged