feat: save tx to basket
novasamatech/nova-spektr pull request #1758
Opened 2024-05-13 10:44 UTC by Asmadek

* create dexie storage for basket transactins
* create basket model
* add buttons to save txs for transfer/staking

2024-05-14 09:50 UTC, pgolovkin approved these changes

2024-05-14 11:17 UTC, sokolova-an approved these changes

2024-05-14 11:17 UTC, sokolova-an commented on src/renderer/entities/transaction/index.ts
> +export * from '../../shared/core/types/transaction';
should we have  just `@shared/core/types/transaction`

2024-05-14 11:17 UTC, sokolova-an commented on src/renderer/entities/transaction/lib/__tests__/transactionConfirmIcon.test.ts
> +import { Transaction, TransactionType } from '../../../../shared/core/types/transaction';
same here and rest of the places with `shared/core/types/transaction`

2024-05-14 11:17 UTC, sokolova-an commented on src/renderer/shared/api/storage/lib/types.ts
> +import { BasketTransaction } from '../../../core/types/basket';
import `BasketTransaction` here and below

2024-05-14 11:17 UTC, sokolova-an commented on src/renderer/widgets/RemoveProxyModal/model/remove-proxy-model.ts
> +import { basketModel } from '@/src/renderer/entities/basket/model/basket-model';
import here and below with `entities/basket/model/basket-model`

2024-05-14 12:31 UTC, tuul-wq requested changes

2024-05-14 12:31 UTC, tuul-wq commented on src/renderer/shared/core/types/basket.ts
> +type Error = ChainError | ClientError;
Take a look at Wallet & specific wallets they have Base interface and concrete wallets with defined types
For `Error` it would look like this
```javascript
export type BasketTransaction = {
  id: ID;
  initiatorWallet: ID;
  coreTx: Transaction;
  txWrappers: TxWrapper[];
  error?: BasketError;
  groupId?: number;
};

interface BasketError {
  type: ErrorType;
  message: string;
}

interface ChainError extends BasketError {
  type: ErrorType.CHAIN;
}

interface ClientError extends BasketError {
  type: ErrorType.CLIENT;
  args?: Record<string, any>;
}
```

2024-05-14 12:31 UTC, tuul-wq commented on src/renderer/entities/basket/model/basket-model.ts
> +const basket = createStore<BasketTransaction[]>([]);
I hoped to see `basketPopulateFx` why don't we do that?

2024-05-14 12:31 UTC, tuul-wq commented on src/renderer/entities/basket/model/basket-model.ts
> +  fn: (basket, transactions) => basket.concat(transactions as BasketTransaction[]),
If `createTxsFx` returns `BasketTransaction[]` why do we call `as BasketTransaction[]`?
Or you didn't want to use `!`?

2024-05-14 12:31 UTC, tuul-wq commented on src/renderer/entities/basket/model/basket-model.ts
> +const createTxsFx = createEffect(
Maybe something like `addBasketTxsFx` or `addBasketTransactionsFx`?

2024-05-14 12:31 UTC, tuul-wq commented on src/renderer/entities/transaction/lib/__tests__/transactionIcon.test.ts
> +import { TransactionType } from '../../../../shared/core/types/transaction';
`@shared/core` doesn't work?

2024-05-14 12:31 UTC, tuul-wq commented on src/renderer/shared/api/storage/lib/types.ts
> +import { BasketTransaction } from '../../../core/types/basket';
`@shared/core`

2024-05-14 12:31 UTC, tuul-wq commented on src/renderer/widgets/Staking/Unstake/model/unstake-model.ts
> +import { BasketTransaction } from '@/src/renderer/shared/core';
Can be shortened

2024-05-14 12:31 UTC, tuul-wq commented on src/renderer/shared/core/types/basket.ts
> +  txWrappers: TxWrapper[];
As I see it will store all this stuff?
```javascript
export type MultisigTxWrapper = {
  kind: WrapperKind.MULTISIG;
  multisigAccount: MultisigAccount;
  signatories: Account[];
  signer: Account;
};

export type ProxyTxWrapper = {
  kind: WrapperKind.PROXY;
  proxyAccount: Account;
  proxiedAccount: ProxiedAccount;
};
```

2024-05-14 12:31 UTC, tuul-wq commented on src/renderer/widgets/AddProxyModal/model/add-proxy-model.ts
> +import { basketModel } from '@entities/basket/model/basket-model';
```suggestion
import { basketModel } from '@entities/basket';
```

2024-05-17 12:32 UTC, tuul-wq approved these changes

2024-05-20 11:11 UTC, merged