feat: add clear all button
novasamatech/nova-spektr pull request #2120
Opened 2024-08-16 15:31 UTC by sokolova-an

2024-08-16 15:43 UTC, johnthecat requested changes

2024-08-16 15:43 UTC, johnthecat commented on src/renderer/features/governance/model/filter.ts
> +sample({
Why not
```ts
const $isFiltersSelected = combine($selectedTrackIds, $selectedVoteId, (tracks, voteId) => {
  return tracks.length > 0 || voteId !== '';
})
```
?

2024-08-19 06:16 UTC, Asmadek approved these changes

2024-08-19 06:16 UTC, Asmadek commented on src/renderer/features/governance/components/ReferendumFilter/ReferendumFilters.tsx
> +      )}{' '}
Why do you need this space here? Doesn't padding or margin work here?

2024-08-19 08:10 UTC, johnthecat approved these changes

2024-08-19 08:23 UTC, merged