Fix: locks calculation with shards
novasamatech/nova-spektr pull request #2205
Opened 2024-08-26 11:58 UTC by sokolova-an

2024-08-26 12:06 UTC, johnthecat commented on src/renderer/features/governance/utils/getLocksForAccount.ts
> +export const getLocksForAccount = (
I think it's better to calculate address outside and rename method `getLocksForAddress`

2024-08-26 12:06 UTC, johnthecat commented on src/renderer/widgets/DelegateModal/model/form-model.ts
> +      init: {} satisfies Record<string, BN>,
It should infer from `FormParams` automatically

2024-08-26 12:06 UTC, johnthecat commented on src/renderer/widgets/DelegateModal/ui/DelegateForm.tsx
> +            <LockValueDiff asset={network.asset} from={accounts[0].lock} to={amountValue} />
`accounts[0]` can return undefined, check it outside JSX

2024-08-26 12:06 UTC, johnthecat commented on src/renderer/widgets/VoteModal/aggregates/voteForm.ts
> +  filter: ({ chain }, account) => !isNil(account) && !isNil(chain),
`nonNullable(account) && nonNullable(chain)`

2024-08-26 12:24 UTC, johnthecat commented on src/renderer/features/governance/utils/getLocksForAccount.ts
> +export const getLocksForAccount = (
Also you can move this helpers into lockService

2024-08-27 08:58 UTC, Asmadek approved these changes

2024-08-27 08:58 UTC, Asmadek commented on src/renderer/features/governance/utils/getLocksForAddress.ts
> +  return Object.values(trackLocks[address]).reduce((max, x) => (max.gte(x) ? max : x), BN_ZERO);
```suggestion
  return Object.values(trackLocks[address]).reduce((max, x) => BN.max(max, x), BN_ZERO);
```

2024-08-27 09:06 UTC, johnthecat requested changes

2024-08-27 09:06 UTC, johnthecat commented on src/renderer/widgets/DelegateModal/model/form-model.ts
> +      return { account: shard, balance: transferableAmount(balance), lock };
Can we switch balance type to `BN` (using `transferableAmountBN`)?

2024-08-27 11:40 UTC, johnthecat approved these changes

2024-08-27 13:49 UTC, merged