feat: rebuild multisig events
novasamatech/nova-spektr pull request #946
Opened 2023-07-05 16:51 UTC by Asmadek

2023-07-06 10:46 UTC, pgolovkin approved these changes

2023-07-07 08:36 UTC, tuul-wq requested changes
Good meaningful addition to the codebase 👍

2023-07-07 08:36 UTC, tuul-wq commented on src/renderer/context/MultisigChainContext/MultisigChainContext.tsx
> +    Object.values(debouncedConnections).filter((c) => c.connection.connectionStatus === ConnectionStatus.CONNECTED)
I assume it's to much for dependency array 😊
Let's make it a variable before `useEffect`

2023-07-07 08:58 UTC, tuul-wq approved these changes

2023-07-07 08:59 UTC, merged